name: Build and Publish Docker images

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push gleam-otp27
      uses: docker/build-push-action@v6
      with:
        context: ./gleam-otp27
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/gleam:latest
          ghcr.io/${{ github.repository_owner }}/gleam:${{ github.sha }}

    - name: Build and push gleam-elixir-otp27
      uses: docker/build-push-action@v6
      with:
        context: ./gleam-elixir-otp27
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/gleam-elixir:latest
          ghcr.io/${{ github.repository_owner }}/gleam-elixir:${{ github.sha }}
